#!/usr/bin/env python3
"""Emit numbers.tex and the generated table fragments for the manuscript.

Every value the paper states in prose must come from here as a LaTeX macro, and
every table is spliced between the `% BEGIN GENERATED <name>` / `% END GENERATED
<name>` markers in paper.tex. Nothing is transcribed by hand — the same
discipline as papers/dare/bench/make_tex_fragments.py.

Run:
  ./.venv/bin/python make_tex_fragments.py --out "../../papers_v3/Entitlement-Aware Routing for Cross-Domain Enterprise AI Agents"
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from common import RESULTS

ROUTER_LABEL = {
    "R1_keyword": ("R1", "Keyword / rule"),
    "R2_embedding": ("R2", "Dense embedding"),
    "R3_llm_blind": ("R3", "LLM, entitlement-blind"),
    "R4_llm_entitled": ("R4", "LLM, entitlements in prompt"),
    "R5_semantic_graph": ("R5", "Semantic graph (KG-guided)"),
    "R6_entitlement_aware": ("R6", "Entitlement-aware (proposed)"),
    "R7_confidence_gated": ("R7", "R6 + confidence gate"),
}
ORDER = list(ROUTER_LABEL)

ABLATION_LABEL = {
    "full": "Full method",
    "no_entitlement": "$-$ data-scope filter",
    "no_feasibility": "$-$ feasibility abstention",
    "no_extraction": "$-$ extraction call",
}


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------
def load(name: str) -> dict:
    return json.loads((RESULTS / name).read_text())


def pct(x: float | None, places: int = 1) -> str:
    return "--" if x is None else f"{100 * x:.{places}f}"


def ci(d: dict | None) -> str:
    """point [low, high] as percentages."""
    if not d:
        return "--"
    return f"{pct(d['point'])} [{pct(d['ci_low'])}, {pct(d['ci_high'])}]"


# Smallest p we are willing to print as a number. Holm adjustment of an already
# tiny exact-binomial p underflows to 0.0 in double precision; printing that as
# "0" would assert certainty the test cannot provide.
P_FLOOR = 1e-15


def pval(p: float | None) -> str:
    if p is None:
        return "--"
    if p >= 0.01:
        return f"{p:.2f}"
    if p < P_FLOOR:
        return "\\ensuremath{<\\!10^{-15}}"
    exp = f"{p:.0e}".replace("e-0", "e-").replace("e+0", "e")
    mant, e = exp.split("e")
    return f"\\ensuremath{{{mant}\\times10^{{{e}}}}}"


_ROMAN = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
          "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def macro_name(raw: str) -> str:
    """LaTeX control sequences admit only letters."""
    out = []
    for ch in raw:
        if ch.isdigit():
            out.append(_ROMAN[ch])
        elif ch.isalpha():
            out.append(ch)
        elif ch in "_- ":
            out.append("")
    return "Ear" + "".join(out)


class Macros:
    def __init__(self) -> None:
        self.items: dict[str, str] = {}

    def add(self, name: str, value: str) -> None:
        key = macro_name(name)
        if key in self.items and self.items[key] != value:
            raise ValueError(f"macro {key} redefined: {self.items[key]!r} vs {value!r}")
        self.items[key] = value

    def render(self) -> str:
        lines = [
            "% GENERATED by papers/ear_bench/make_tex_fragments.py -- do not edit.",
            "% Every number the manuscript states in prose is defined here.",
            "",
        ]
        for key in sorted(self.items):
            lines.append(f"\\newcommand{{\\{key}}}{{{self.items[key]}}}")
        return "\n".join(lines) + "\n"


def table(caption: str, label: str, spec: str, header: list[str],
          rows: list[list[str]], note: str = "", size: str = "small",
          colsep: str | None = None) -> str:
    out = [
        "\\begin{table}[t]",
        f"\\caption{{{caption}}}\\label{{{label}}}",
        "\\centering",
        f"\\{size}",
        *( [f"\\setlength{{\\tabcolsep}}{{{colsep}}}"] if colsep else [] ),
        f"\\begin{{tabular}}{{{spec}}}",
        "\\toprule",
        " & ".join(header) + " \\\\",
        "\\midrule",
    ]
    out += [" & ".join(r) + " \\\\" for r in rows]
    out += ["\\bottomrule", "\\end{tabular}"]
    if note:
        out.append("\\\\[3pt]")
        out.append(f"\\begin{{minipage}}{{\\linewidth}}\\footnotesize {note}\\end{{minipage}}")
    out.append("\\end{table}")
    return "\n".join(out)


# --------------------------------------------------------------------------
# fragments
# --------------------------------------------------------------------------
def build(m: Macros) -> dict[str, str]:
    char = load("characterization.json")
    bench = load("benchmark_summary.json")
    main = load("analysis_haiku.json")
    res_main = load("router_results_haiku.json")
    res_shuf = load("router_results_haiku_shuffled_0.json")
    res_sonnet = load("router_results_sonnet_transfer.json")
    policy = load("policy_sensitivity.json")
    abl = load("ablations_haiku.json")
    filt = load("filtered_baselines_haiku.json")
    err = load("error_analysis_haiku.json")
    bounds = load("reference_bounds.json")
    var = load("router_results_haiku_t0.7_s202.json")
    cross = load("cross_arm.json")
    opaque = load("router_results_haiku_opaque.json")
    pairs = load("pairs_analysis.json")
    pairs_sum = load("benchmark_pairs_summary.json")

    frags: dict[str, str] = {}

    # ---- corpus and benchmark -------------------------------------------
    m.add("tasks-total", str(char["tasks_total"]))
    m.add("tasks-labelled", str(char["tasks_labelled"]))
    m.add("labelled-pct", f"{100*char['labelled_fraction']:.1f}")
    m.add("databases", str(char["distinct_databases"]))
    m.add("gold-tool-sets", str(char["distinct_gold_tool_sets"]))
    m.add("route-len-mean", f"{char['route_length']['mean']:.2f}")
    m.add("db-disagree", str(char["tasks_with_db_column_disagreement"]))
    m.add("sql-alias-tasks", str(char["sql_alias_normalised_tasks"]))
    m.add("instances", str(bench["instances"]))
    m.add("domains", str(len(bench["domain_task_counts"])))
    m.add("principals", str(len(bench["principal_usage"])))
    for st, n in bench["strata_overall"].items():
        m.add(f"stratum-{st.lower()}", str(n))
    m.add("eval-tasks", str(res_main["eval_tasks"]))
    m.add("eval-instances", str(res_main["eval_instances"]))
    m.add("calib-tasks", str(res_main["calibration_tasks"]))
    for tool, d in char["governed_tool_coverage"].items():
        m.add(f"cover-{tool}", f"{d['pct']:.1f}")

    # ---- routers ---------------------------------------------------------
    desc = {
        "R1_keyword": "Lexical cues; no model call.",
        "R2_embedding": "Query--tool cosine, calibrated thresholds.",
        "R3_llm_blind": "LLM picks tools; no entitlements.",
        "R4_llm_entitled": "LLM gets full scope; may abstain.",
        "R5_semantic_graph": "Domain--tool propagation; permission-blind.",
        "R6_entitlement_aware": "One extraction, then explicit resolution.",
        "R7_confidence_gated": "R6 plus a calibrated confidence gate.",
    }
    frags["tab_routers"] = table(
        caption="Routers compared. Only R4, R6 and R7 observe entitlements.",
        label="tab:routers", spec="llcp{40mm}",
        header=["", "Router", "Entitl.\\ aware", "Mechanism"],
        rows=[
            [ROUTER_LABEL[r][0], ROUTER_LABEL[r][1],
             "yes" if r in {"R4_llm_entitled", "R6_entitlement_aware", "R7_confidence_gated"} else "no",
             desc[r]]
            for r in ORDER
        ],
        note=(
            "R6 issues one model call per query regardless of how many principals "
            "ask it; R4 requires one per (query, principal) pair, a $k$-fold "
            "difference at $k$ principals."
        ),
    )

    # ---- main results ----------------------------------------------------
    rows = []
    for r in ORDER:
        e = main["routers"][r]
        ab = e["abstention"]
        rows.append([
            ROUTER_LABEL[r][0],
            ci(e["overall"]["over_reach"]),
            pct(e["overall"]["safe"]["point"]),
            pct(e["overall"]["useful"]["point"]),
            f"{res_main['results'][r]['overall']['tool_set_f1']:.3f}",
            pct(ab["precision"]["point"]) if ab["precision"]["n"] else "--",
            pct(ab["recall"]["point"]),
        ])
        m.add(f"overreach-{r}", pct(e["overall"]["over_reach"]["point"], 2))
        m.add(f"safe-{r}", pct(e["overall"]["safe"]["point"]))
        m.add(f"useful-{r}", pct(e["overall"]["useful"]["point"]))
    # Filtered-baseline rows share this table's structure; merging them saves a
    # float and puts the key comparison beside the routers it concerns.
    for name in ("R3+filter", "R4+filter"):
        e = filt["routers"][name]
        rows.append([
            name.replace("+", "$+$"),
            ci(e["over_reach"]), pct(e["safe"]["point"]),
            pct(e["useful"]["point"]), "--", "--", "--",
        ])
    frags["tab_main"] = table(
        caption=(
            "Main results, Claude Haiku 4.5, "
            f"{res_main['eval_instances']} instances. Over-reach carries a 95\\% "
            "Wilson interval; other columns are point estimates. The last two "
            "rows apply the same post-hoc entitlement filter to R3 and R4."
        ),
        label="tab:main", spec="lcccccc", size="footnotesize", colsep="3pt",
        header=["", "Over-reach", "Safe", "Useful", "Tool $F_1$",
                "Abst.\\ prec.", "Abst.\\ rec."],
        rows=rows,
        note=(
            "Usefulness is defined on feasible instances only. Filtering drives "
            "over-reach to zero for either source router, with no discordant "
            "instance against R6; the residual difference is safety, not reach."
        ),
    )

    # ---- filtered baselines ---------------------------------------------
    order_f = ["R3_llm_blind", "R3+filter", "R4_llm_entitled", "R4+filter",
               "R6_entitlement_aware"]
    rows = []
    for name in order_f:
        e = filt["routers"][name]
        label = ROUTER_LABEL.get(name, (name, name))[0] if name in ROUTER_LABEL else name
        rows.append([label.replace("+", "$+$"), ci(e["over_reach"]), ci(e["safe"]), ci(e["useful"])])
    for name in ("R3+filter", "R4+filter"):
        key = name.replace("+", "plus")
        m.add(f"overreach-{key}", pct(filt["routers"][name]["over_reach"]["point"], 2))
        m.add(f"safe-{key}", pct(filt["routers"][name]["safe"]["point"]))
        m.add(f"pfiltersafe-{key}", pval(filt["vs_reference"][name]["safe"]["p_value"]))
        m.add(f"pfilteruseful-{key}", pval(filt["vs_reference"][name]["useful"]["p_value"]))

    # ---- policy sensitivity (headline) -----------------------------------
    ARMS = [("declared", None), ("opaque_principals", "opaque"),
            ("shuffled_seed0", "shuffle 0"), ("shuffled_seed1", "shuffle 1"),
            ("shuffled_seed2", "shuffle 2")]
    rows = []
    for router in ("R4_llm_entitled", "R6_entitlement_aware"):
        tag = ROUTER_LABEL[router][0]
        for cell, cellname in (("INFEASIBLE_SCOPE:over_reach", "scope over-reach"),
                               ("FEASIBLE:abstained", "false abstention")):
            cells = [tag, cellname]
            first = cross["opaque_principals"][router][cell]["declared_rate"]
            cells.append(pct(first["point"]))
            for key, _lbl in ARMS[1:]:
                v = cross[key][router][cell]["arm"]
                cells.append(pct(v["point"]))
            rows.append(cells)
    frags["tab_policy"] = table(
        caption=(
            "Policy sensitivity. Stratum-conditional rates under the declared "
            "policy, under opaque principal names, and under three independent "
            "shuffled policies. Opaque naming severs the semantic cue without "
            "inducing conflict; shuffling inverts it."
        ),
        label="tab:policy", spec="llccccc",
        header=["", "Measure", "Declared", "Opaque", "Shuf.\\,0", "Shuf.\\,1", "Shuf.\\,2"],
        rows=rows,
        note=(
            "Percentages. Arms have different stratum sizes, so only "
            "stratum-conditional rates are comparable; each is paired against the "
            "declared arm on shared instances (Section~\\ref{sec:results})."
        ),
    )

    # ---- backbone transfer ----------------------------------------------
    rows = []
    for r in ORDER:
        a = res_main["results"][r]["overall"]
        b = res_sonnet["results"][r]["overall"]
        rows.append([
            ROUTER_LABEL[r][0],
            pct(a["over_reach_rate"], 2), pct(b["over_reach_rate"], 2),
            pct(a["safe_rate"]), pct(b["safe_rate"]),
            pct(a["useful_rate"]), pct(b["useful_rate"]),
        ])
    m.add("sonnet-overreach-RFour", pct(res_sonnet["results"]["R4_llm_entitled"]["overall"]["over_reach_rate"], 2))
    m.add("sonnet-overreach-RSix", pct(res_sonnet["results"]["R6_entitlement_aware"]["overall"]["over_reach_rate"], 2))
    m.add("model-main", res_main["model"].replace("_", "\\_"))
    m.add("model-transfer", res_sonnet["model"].replace("_", "\\_"))
    # Short forms for prose: the full ids are unbreakable in \texttt and
    # overflow the LNCS text block by ~110pt.
    m.add("model-main-short", "Haiku 4.5")
    m.add("model-transfer-short", "Sonnet 4.5")
    frags["tab_transfer"] = table(
        caption="Backbone transfer: Haiku 4.5 (H) and Sonnet 4.5 (S).",
        label="tab:transfer", spec="lcccccc",
        header=["", "O-R H", "O-R S", "Safe H", "Safe S", "Use.\\ H", "Use.\\ S"],
        rows=rows,
        note=(
            "R1, R2 and R5 make no model call and are unchanged. R4 over-reaches "
            "\\emph{more} on the stronger backbone."
        ),
    )

    # ---- ablations -------------------------------------------------------
    rows = [
        [ABLATION_LABEL[a], ci(abl["arms"][a]["over_reach"]),
         ci(abl["arms"][a]["safe"]), ci(abl["arms"][a]["useful"])]
        for a in ABLATION_LABEL
    ]
    for a in ABLATION_LABEL:
        m.add(f"abl-overreach-{a}", pct(abl["arms"][a]["over_reach"]["point"]))
        m.add(f"abl-safe-{a}", pct(abl["arms"][a]["safe"]["point"]))
        m.add(f"abl-useful-{a}", pct(abl["arms"][a]["useful"]["point"]))
    frags["tab_ablation"] = table(
        caption="Ablations of the proposed router. Deterministic re-scoring; no model calls.",
        label="tab:ablation", spec="lccc",
        header=["Arm", "Over-reach", "Safe", "Useful"],
        rows=rows,
    )

    # ---- prose numbers ---------------------------------------------------
    cmp_ = main["comparisons"]
    for key in ("over_reach", "safe", "useful"):
        c = cmp_[f"R6_entitlement_aware_vs_R4_llm_entitled__{key}"]
        m.add(f"mcnemar-{key}-p", pval(c.get("p_holm", c.get("p_value"))))
        m.add(f"mcnemar-{key}-rsix", str(c["a_only"]))
        m.add(f"mcnemar-{key}-rfour", str(c["b_only"]))

    blind = bounds["R0b_permission_blind_oracle"]
    m.add("oracle-blind-overreach", pct(blind["overall"]["over_reach_rate"]))
    m.add("oracle-blind-foreign", pct(blind["C_foreign"]["over_reach_rate"]))

    e4 = err["R4_llm_entitled"]
    m.add("rfour-overreach-n", str(e4["over_reach"]["n"]))
    m.add("rfour-falseabs-n", str(e4["false_abstention"]["n"]))
    m.add("rfour-falseabs-admin", str(e4["false_abstention"]["by_principal"].get("platform_admin", 0)))
    m.add("rfour-missedabs-n", str(e4["missed_abstention"]["n"]))
    # How concentrated the negative result is: the largest single principal.
    m.add("rfour-concentrated-n", str(max(e4["over_reach"]["by_principal"].values())))
    m.add("rsix-missedabs-n", str(err["R6_entitlement_aware"]["missed_abstention"]["n"]))
    m.add("rsix-falseabs-n", str(err["R6_entitlement_aware"]["false_abstention"]["n"]))

    cal = res_main["r7_calibration"]["calibration_confidence"]
    m.add("conf-min", f"{cal['min']:.2f}")
    m.add("conf-max", f"{cal['max']:.2f}")
    m.add("conf-mean", f"{cal['mean']:.3f}")
    m.add("rseven-threshold", f"{res_main['r7_calibration']['chosen']:.1f}")

    total_calls = sum(
        d["usage"]["calls"]
        for d in (res_main, res_shuf, res_sonnet, var)
    ) + 585
    total_cost = sum(
        d["usage"]["est_cost_usd"]
        for d in (res_main, res_shuf, res_sonnet, var)
    ) + 0.5721
    m.add("total-calls", f"{total_calls:,}")
    m.add("total-cost", f"{total_cost:.2f}")
    m.add("variance-seeds", str(var["seeds"]))
    m.add("variance-temp", f"{var['temperature']:g}")

    # ---- opaque-principal control and multi-seed shuffle -----------------
    op = cross["opaque_principals"]["R4_llm_entitled"]
    m.add("opaque-scope-RFour", pct(op["INFEASIBLE_SCOPE:over_reach"]["arm"]["point"]))
    m.add("opaque-scope-p", pval(op["INFEASIBLE_SCOPE:over_reach"]["mcnemar"].get("p_holm")))
    m.add("opaque-falseabs-RFour", pct(op["FEASIBLE:abstained"]["arm"]["point"]))
    m.add("opaque-falseabs-p", pval(op["FEASIBLE:abstained"]["mcnemar"].get("p_holm")))
    m.add("opaque-n-scope", str(op["INFEASIBLE_SCOPE:over_reach"]["mcnemar"]["n_paired"]))
    m.add("opaque-n-feasible", str(op["FEASIBLE:abstained"]["mcnemar"]["n_paired"]))
    og = cross["opaque_principals"]["R6_entitlement_aware"]
    m.add("opaque-scope-RSix", pct(og["INFEASIBLE_SCOPE:over_reach"]["arm"]["point"]))

    seeds = [k for k in cross if k.startswith("shuffled_seed")]
    sc = [cross[k]["R4_llm_entitled"]["INFEASIBLE_SCOPE:over_reach"]["arm"]["point"] for k in sorted(seeds)]
    m.add("scope-shuffled-RFour", pct(cross["shuffled_seed0"]["R4_llm_entitled"]["INFEASIBLE_SCOPE:over_reach"]["arm"]["point"]))
    fa = [cross[k]["R4_llm_entitled"]["FEASIBLE:abstained"]["arm"]["point"] for k in sorted(seeds)]
    m.add("shuffle-seeds", str(len(seeds)))
    m.add("shuffle-scope-min", pct(min(sc)))
    m.add("shuffle-scope-max", pct(max(sc)))
    m.add("shuffle-falseabs-min", pct(min(fa)))
    m.add("shuffle-falseabs-max", pct(max(fa)))
    for i, k in enumerate(sorted(seeds)):
        m.add(f"shuffle-scope-seed{'abc'[i]}", pct(cross[k]["R4_llm_entitled"]["INFEASIBLE_SCOPE:over_reach"]["arm"]["point"]))
        m.add(f"shuffle-falseabs-seed{'abc'[i]}", pct(cross[k]["R4_llm_entitled"]["FEASIBLE:abstained"]["arm"]["point"]))

    # declared-arm reference rates referenced in prose
    ps = load("policy_sensitivity.json")
    for router, tag in (("R4_llm_entitled", "RFour"), ("R6_entitlement_aware", "RSix")):
        d = ps["over_reach_by_stratum"][router]
        m.add(f"scope-declared-{tag}", pct(d["INFEASIBLE_SCOPE"]["declared"]["point"]))
        m.add(f"scopetool-declared-{tag}", pct(d["INFEASIBLE_TOOL"]["declared"]["point"]))
        m.add(f"scopetool-shuffled-{tag}", pct(d["INFEASIBLE_TOOL"]["shuffled"]["point"]))
        f = ps["false_abstention_on_feasible"][router]
        m.add(f"falseabs-declared-{tag}", pct(f["declared"]["point"]))

    # How much the shuffle moves principal assignment -- the three-factor caveat.
    import json as _json
    D = {(r["task_id"], r["condition"]): r
         for r in map(_json.loads, (RESULTS / "benchmark.jsonl").open())}
    S = {(r["task_id"], r["condition"]): r
         for r in map(_json.loads, (RESULTS / "benchmark_shuffled_0.jsonl").open())}
    keys = [k for k in D if k[1] != "A_unrestricted" and k in S]
    changed = sum(1 for k in keys if D[k]["principal"] != S[k]["principal"])
    m.add("shuffle-principal-change", f"{100*changed/len(keys):.0f}")

    # ---- backbone transfer, now tested -----------------------------------
    bt = cross["backbone_transfer"]
    m.add("transfer-p-RFour", pval(bt["R4_llm_entitled"]["mcnemar"].get("p_holm")))
    m.add("transfer-p-RThree", pval(bt["R3_llm_blind"]["mcnemar"].get("p_holm")))
    m.add("sonnet-overreach-RThree", pct(bt["R3_llm_blind"]["sonnet"]["point"], 2))
    m.add("haiku-overreach-RThree", pct(bt["R3_llm_blind"]["haiku"]["point"], 2))

    # ---- what the usefulness comparison can exclude ----------------------
    ui = cross["usefulness_interval"]["R6_minus_R4"]
    m.add("useful-diff-mean", f"{ui['mean_pp']:+.1f}")
    m.add("useful-diff-low", f"{abs(ui['ci_low_pp']):.1f}")
    m.add("useful-diff-high", f"{ui['ci_high_pp']:+.1f}")

    # ---- construction bounds, recomputed on the EVAL set -----------------
    import collections
    rows = [json.loads(l) for l in (RESULTS / "decisions_haiku.jsonl").open()]
    one = [r for r in rows if r["router"] == "R6_entitlement_aware"]
    st = collections.Counter(r["stratum"] for r in one)
    infeas = st["INFEASIBLE_SCOPE"] + st["INFEASIBLE_TOOL"]
    m.add("bound-infeasible-eval", pct(infeas / len(one)))
    m.add("bound-eval-n", str(len(one)))

    # ---- ablation significance ------------------------------------------
    for a_name in ("no_entitlement", "no_feasibility", "no_extraction"):
        for key in ("safe", "useful"):
            r = abl["vs_full"][a_name][key]
            if "p_value" in r:
                m.add(f"ablp-{a_name}-{key}", pval(r.get("p_holm", r["p_value"])))

    # ---- filtered baselines, Holm-adjusted -------------------------------
    for nm in ("R3+filter", "R4+filter"):
        key = nm.replace("+", "plus")
        m.add(f"pfilterholm-{key}",
              pval(filt["vs_reference"][nm]["safe"].get("p_holm")))
        m.add(f"pfilterusefulholm-{key}",
              pval(filt["vs_reference"][nm]["useful"].get("p_holm")))

    # ---- paired permit/revoke control ------------------------------------
    PAIR_LABEL = {"D_domain": "data domain", "A_web": "web-search",
                  "B_vector": "vector-search", "D_web_vector": "web + vector"}
    PAIR_KEY = {"D_domain": "domain", "A_web": "web",
                "B_vector": "vector", "D_web_vector": "webvector"}
    rows = []
    for cfg in ("D_domain", "A_web", "B_vector", "D_web_vector"):
        if cfg not in pairs["configs"]:
            continue
        e = pairs["configs"][cfg]
        r4 = e["routers"]["R4_llm_entitled"]
        r6 = e["routers"]["R6_entitlement_aware"]
        rows.append([
            PAIR_LABEL[cfg], str(r4["n_revoke"]),
            ci(r4["over_reach_revoke"]), ci(r4["false_abstention_permit"]),
            ci(r6["over_reach_revoke"]), ci(r6["false_abstention_permit"]),
        ])
        k = PAIR_KEY[cfg]
        m.add(f"pair-over-RFour-{k}", pct(r4["over_reach_revoke"]["point"]))
        m.add(f"pair-over-RSix-{k}", pct(r6["over_reach_revoke"]["point"]))
        m.add(f"pair-fabs-RFour-{k}", pct(r4["false_abstention_permit"]["point"]))
        m.add(f"pair-n-{k}", str(r4["n_revoke"]))
        if "invoked_permit" in r4:
            m.add(f"pair-inv-permit-{k}", pct(r4["invoked_permit"]))
            m.add(f"pair-inv-revoke-{k}", pct(r4["invoked_revoke"]))
    # Per-principal cells for the capability-vs-principal argument. Hand-typing
    # these in prose would bypass the numeric guard.
    import json as _j
    _bench = {i["instance_id"]: i for i in
              map(_j.loads, (RESULTS / "benchmark_pairs.jsonl").open())}
    _dec = {r["instance_id"]: r for r in
            map(_j.loads, (RESULTS / "decisions_haiku_pairs.jsonl").open())
            if r["router"] == "R4_llm_entitled"}
    _cell = {}
    for iid, inst in _bench.items():
        if inst["arm"] != "REVOKE" or iid not in _dec:
            continue
        k = (inst["config"], inst["principal"])
        a, b = _cell.get(k, (0, 0))
        _cell[k] = (a + bool(_dec[iid]["over_reach"]), b + 1)
    for cfg, key in PAIR_KEY.items():
        hit = _cell.get((cfg, "commerce_analyst"))
        if hit and hit[1]:
            m.add(f"pair-commerce-{key}", pct(hit[0] / hit[1]))
    acc = pairs["pair_accounting"]
    m.add("pair-built", str(acc["built"]))
    m.add("pair-evaluated", str(acc["evaluated"]))
    m.add("pair-heldout", str(acc["held_out_in_calibration"]))
    m.add("pair-principals-vector",
          str(sum(1 for c in pairs["per_principal"]["B_vector"].values() if c["n_revoke"])))
    m.add("pair-total", str(sum(pairs_sum["pairs"].values())))
    m.add("pair-configs", str(len(pairs_sum["pairs"])))
    m.add("pair-filesystem-tasks", str(char["governed_tool_coverage"]["file_system"]["tasks"]))
    frags["tab_pairs"] = table(
        caption=(
            "Paired permit/revoke control. One entitlement that the gold route "
            "requires is toggled; everything else in the pair is held fixed. "
            "Over-reach is measured on the revoked member, false abstention on "
            "the permitted member."
        ),
        label="tab:pairs", spec="lrcccc",
        header=["Revoked", "$n$", "R4 over-reach", "R4 false abst.",
                "R6 over-reach", "R6 false abst."],
        rows=rows,
        note=(
            "Percentages with 95\\% Wilson intervals. A \\texttt{file\\_system} "
            "configuration is not reported: no non-administrative principal can "
            "host such a pair (Section~\\ref{sec:threats})."
        ),
    )

    return frags


# --------------------------------------------------------------------------
def splice(tex: Path, frags: dict[str, str]) -> list[str]:
    src = tex.read_text()
    touched = []
    for name, body in frags.items():
        begin, end = f"% BEGIN GENERATED {name}", f"% END GENERATED {name}"
        pattern = re.compile(
            re.escape(begin) + r".*?" + re.escape(end), re.S
        )
        if not pattern.search(src):
            continue
        # Callable replacement: LaTeX bodies are full of backslashes, which
        # re.sub would otherwise interpret as escape sequences.
        src = pattern.sub(lambda _m, b=body: f"{begin}\n{b}\n{end}", src)
        touched.append(name)
    tex.write_text(src)
    return touched


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", required=True, help="paper directory")
    args = ap.parse_args()
    out = Path(args.out).resolve()

    m = Macros()
    frags = build(m)
    (out / "numbers.tex").write_text(m.render())

    frag_dir = out / "generated"
    frag_dir.mkdir(exist_ok=True)
    for name, body in frags.items():
        (frag_dir / f"{name}.tex").write_text(body + "\n")

    touched = splice(out / "paper.tex", frags)
    missing = sorted(set(frags) - set(touched))

    print(f"wrote {out/'numbers.tex'}  ({len(m.items)} macros)")
    print(f"wrote {len(frags)} fragments to {frag_dir}")
    print(f"spliced into paper.tex: {', '.join(touched) if touched else '(none)'}")
    if missing:
        print(f"NOT spliced (no markers in paper.tex): {', '.join(missing)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
